### ISSUE TITLE
PyQt5 usage

### ISSUE THREAD

**Issue by tmontaigu** [tmontaigu/CloudCompare-PythonRuntime#39]
PyQt5 should be usable to allow scripts / plugins to be interactive.

However it does not quite work at the moment, and it might be difficult to make it work

On windows, when installed via `pip` any import like `from PyQt5.QtWidgets import QApplication, QDialog, QMessageBox`
will make CC crash. ❌

On linux when installed via pip, it does not crash, but instead we have an import error, with a message about  
`undefined symbol: _ZdlPvm`, indicating a possible binary incompatibility (gcc used to produce PyQt wheel might be to old) ❌

On linux when installed via the distro's package manager (eg `dnf install python3-pyqt5-sip.x86_64`) it works ✅

So probably, if we want PyQt5 to work we'll have to compile it from source to match with the rest of the toolchain and Qt version used

**Comment by rjanvier** [comment]
Hi Thomas. I noticed an issue with the usage of PyQt in a "plugin context".
Here is a sample to reproduce the issue.

```python
from PyQt5.QtWidgets import QWidget

win = QWidget()
win.setWindowTitle("PyQT win")
win.show()
```

if you execute this code from the CC-PythonPlugin interpreter all is running fine. but if you wrap this into an action inside a Python Plugin the window won't show up or at most "blink" (you can add a `sleep(n)` to see it for n second). My guess is that maybe because `show()` is asynchronous `PythonInterpreter::executeFunction` will return early and destroy the window. What do you think on your side? What can we do to mitigate this issue?

**Comment by tmontaigu** [comment]
I remebered I forgot to answer to this.

It is expected that this code shows the windo only for a fraction of second.

To make it work in a plugin you have to do:


```Python
import pycc

from typing import List
from pathlib import Path
from PyQt5.QtWidgets import QWidget
from time import sleep

class Window(pycc.PythonPluginInterface):
    def __init__(self):
        pycc.PythonPluginInterface.__init__(self)
        self.count = 0
        self.app = pycc.GetInstance()
        
        self.win = QWidget()
        self.win.setWindowTitle("PyQT win")

    def getActions(self) -> List[pycc.Action]:
        return [
            pycc.Action(name="Show Windows", target=self.showWindow),
        ]

    def showWindow(self):
        self.win.show()
```
